//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Ping", ReplyAction="http://tempuri.org/ITestService/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Ping", ReplyAction="http://tempuri.org/ITestService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoLongRunningOperation", ReplyAction="http://tempuri.org/ITestService/DoLongRunningOperationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ITestService/DoLongRunningOperationStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        string DoLongRunningOperation(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/DoLongRunningOperation", ReplyAction="http://tempuri.org/ITestService/DoLongRunningOperationResponse")]
        System.Threading.Tasks.Task<string> DoLongRunningOperationAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/AbortLongRunningOperation", ReplyAction="http://tempuri.org/ITestService/AbortLongRunningOperationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ITestService/AbortLongRunningOperationStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        void AbortLongRunningOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/AbortLongRunningOperation", ReplyAction="http://tempuri.org/ITestService/AbortLongRunningOperationResponse")]
        System.Threading.Tasks.Task AbortLongRunningOperationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : Client.ServiceReferences.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<Client.ServiceReferences.ITestService>, Client.ServiceReferences.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public string DoLongRunningOperation(string input) {
            return base.Channel.DoLongRunningOperation(input);
        }
        
        public System.Threading.Tasks.Task<string> DoLongRunningOperationAsync(string input) {
            return base.Channel.DoLongRunningOperationAsync(input);
        }
        
        public void AbortLongRunningOperation() {
            base.Channel.AbortLongRunningOperation();
        }
        
        public System.Threading.Tasks.Task AbortLongRunningOperationAsync() {
            return base.Channel.AbortLongRunningOperationAsync();
        }
    }
}
